# Generated by Django 5.2.1 on 2025-05-23 04:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='note',
            name='noteheading',
            field=models.CharField(default='Untitled note', max_length=200),
        ),
    ]
